### ISSUE TITLE
swift?

### ISSUE THREAD

**Issue by idkjs** [iawaknahc/plist#1]
I found this repo looking for an example of binding ocaml/reasonml to swift code.

What does this project do?

Thanks for sharing it.

**Comment by iawaknahc** [comment]
> What does this project do?

This project is a CLI program that does what `genstrings` does. It scans invocation of `NSLocalizedString` and generates `Localizable.strings` files. It is written in OCaml.

> I found this repo looking for an example of binding ocaml/reasonml to swift code.

I am sorry that this project may not be something you are looking for.

**Comment by idkjs** [comment]
Thank you, sir.
